# Generated by Django 5.2.11 on 2026-04-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
